# Generated by Django 3.1.7 on 2021-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamrin', '0004_article_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, upload_to='tamrin/tamrin_pdf'),
        ),
    ]
