# Generated by Django 3.1.7 on 2021-03-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamrin', '0005_auto_20210307_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vid',
            field=models.FileField(blank=True, upload_to='tamrin/tamrin_pdf'),
        ),
    ]
